version: "3.8"
services:
  app:
    container_name: server
    build:
        context: .
        dockerfile: dockerfile
    volumes:
      - ./:/app
    ports:
      - "80:80"
      - "443:443"
      - "5000:5000"